version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - user-net
    restart: always
  mysqlservice:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysqlservice
    networks:
      - user-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: user


  mongo-service:
    image: mongo:latest
    container_name: bankmongo-container
    networks:
      - user-net
    ports:
      - "27017:27017"

  fundauth:
    container_name: fundauth
    build: FundAuth/
    networks:
      - user-net
    ports:
      - "6060:6060"
    depends_on:
      - mysqlservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlservice:3306/user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
    restart: always

  fundstartup:
    container_name: fundstartup
    build: FundStartup/
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - user-net
    ports:
      - "6062:6062"
    depends_on:
      - mongo-service
    restart: always

  fundinvest:
    container_name: fundinvest
    build: fundInvest/
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - user-net
    ports:
      - "6061:6061"
    depends_on:
      - mongo-service

networks:
  user-net:
    driver: bridge